name: Ping Telegram (no code changes)
on:
  workflow_dispatch: {}   # run manually

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Send test message
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          set -e
          if [ -z "$TELEGRAM_BOT_TOKEN" ] || [ -z "$TELEGRAM_CHAT_ID" ]; then
            echo "Missing TELEGRAM_BOT_TOKEN or TELEGRAM_CHAT_ID"; exit 1
          fi
          MSG="✅ Telegram test — GitHub Actions can send messages."
          curl -sS -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
            -d chat_id="${TELEGRAM_CHAT_ID}" \
            --data-urlencode text="$MSG" \
            -d parse_mode=Markdown
          echo "Sent."
