name: TD Alerts (Anytime & First Team)
on:
  schedule:
    # Runs every 15 min Thu–Mon. (UTC schedule; it's fine, code filters by today's games.)
    - cron: "*/15 * * * 4-1"
  workflow_dispatch: {}
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - run: pip install -r requirements.txt
    - env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        ODDS_API_KEY: ${{ secrets.ODDS_API_KEY }}
      run: python -c "from src.td_alerts import run_td_alerts; run_td_alerts()"
